"""Generate HandType launcher foreground vector drawable from a font glyph."""
import sys
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import RecordingPen

FONT = r"C:\Windows\Fonts\SitkaVF-Italic.ttf"
TARGET_H = 60.0
X_OFFSET = 2.0
CY_BASELINE = 76.0
OUT = r"app/src/main/res/drawable/ic_launcher_foreground.xml"

font = TTFont(FONT)
cmap = font.getBestCmap()
gset = font.getGlyphSet()
glyph = gset[cmap[ord('h')]]
pen = RecordingPen()
glyph.draw(pen)

xs, ys = [], []
for cmd, pts in pen.value:
    for p in pts:
        xs.append(p[0]); ys.append(p[1])
minx, maxx = min(xs), max(xs)
miny, maxy = min(ys), max(ys)
scale = TARGET_H / (maxy - miny)
cx = 54.0 + X_OFFSET

def tx(x): return cx + (x - (minx + maxx) / 2.0) * scale
def ty(y): return CY_BASELINE - y * scale

parts = []
for cmd, pts in pen.value:
    if cmd == 'moveTo':
        x, y = pts[0]; parts.append(f"M{tx(x):.2f},{ty(y):.2f}")
    elif cmd == 'lineTo':
        x, y = pts[0]; parts.append(f"L{tx(x):.2f},{ty(y):.2f}")
    elif cmd == 'qCurveTo':
        ctrl = None
        for p in pts:
            if ctrl is None:
                ctrl = p
            else:
                parts.append(f"Q{tx(ctrl[0]):.2f},{ty(ctrl[1]):.2f} {tx(p[0]):.2f},{ty(p[1]):.2f}")
                ctrl = None
    elif cmd == 'curveTo':
        c1, c2, end = pts
        parts.append(f"C{tx(c1[0]):.2f},{ty(c1[1]):.2f} {tx(c2[0]):.2f},{ty(c2[1]):.2f} {tx(end[0]):.2f},{ty(end[1]):.2f}")
    elif cmd == 'closePath':
        parts.append("Z")

glyph_path = " ".join(parts)

xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- HandType launcher foreground: italic calligraphic 'h' (Sitka Italic).
     Generated by gen_icon.py: glyph extracted via fontTools, fitted to 108x108 viewport.
     target_h={TARGET_H}, x_offset={X_OFFSET}, baseline={CY_BASELINE}. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <path
        android:pathData="{glyph_path}"
        android:fillColor="#1A1410" />

    <!-- Amber signature flourish under glyph -->
    <path
        android:pathData="M30 84 C 44 81, 64 80, 80 83"
        android:strokeColor="#B8742E"
        android:strokeWidth="3.0"
        android:strokeLineCap="round"
        android:fillColor="#00000000" />
</vector>
'''
open(OUT, 'w', encoding='utf-8').write(xml)
print(f"wrote {OUT} ({len(xml)} bytes, glyph path {len(glyph_path)} chars)")
